[target.xtensa-esp32s3-espidf]
runner = "espflash flash --monitor"

[build]
target = "xtensa-esp32s3-espidf"

[env]
ESP_LOGLEVEL = "INFO"
ESP_IDF_VERSION = "v5.3"

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[alias]
# Common development commands
build-esp = "build --target xtensa-esp32s3-espidf"
flash = "run --target xtensa-esp32s3-espidf"
size = "size --target xtensa-esp32s3-espidf --release"