[target.xtensa-esp32s3-espidf]
runner = "espflash flash --monitor"
linker = "/Users/justin/Documents/Github/ESP32-S3-Display-Dashboard/gcc-wrapper.sh"
rustflags = [
    # Temporarily disable gc-sections to preserve app descriptor
    # "-C", "link-arg=-Wl,--gc-sections",
    # Enable frame pointers for better debugging in release
    "-C", "force-frame-pointers=yes",
]

[build]
target = "xtensa-esp32s3-espidf"

[env]
# Reduce logging in release builds
ESP_LOGLEVEL = { value = "WARN", force = false }
ESP_IDF_VERSION = "v5.3.3"
IDF_PATH = "/Users/justin/.espressif/esp-idf/v5.3"
# Set Rust log level based on profile
RUST_LOG = { value = "warn", force = false }

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[alias]
# Common development commands
build-esp = "build --target xtensa-esp32s3-espidf"
flash = "run --target xtensa-esp32s3-espidf"
size = "size --target xtensa-esp32s3-espidf --release"