[target.xtensa-esp32s3-espidf]
runner = "espflash flash --monitor"
linker = "ldproxy"
rustflags = [
    # Removed frame pointers flag due to CC compatibility issues
]

[build]
target = "xtensa-esp32s3-espidf"

[env]
# Reduce logging in release builds
ESP_LOGLEVEL = { value = "WARN", force = false }
ESP_IDF_VERSION = "v5.3.3"
IDF_PATH = "/Users/justin/.espressif/esp-idf/v5.3"
# Set Rust log level based on profile
RUST_LOG = { value = "warn", force = false }

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[alias]
# Common development commands
build-esp = "build --target xtensa-esp32s3-espidf"
flash = "run --target xtensa-esp32s3-espidf"
size = "size --target xtensa-esp32s3-espidf --release"