name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rust-docs

      - name: Install ESP-IDF dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util

      - name: Cache ESP-IDF
        uses: actions/cache@v3
        with:
          path: ~/.espressif
          key: ${{ runner.os }}-esp-idf-v5.1
          restore-keys: |
            ${{ runner.os }}-esp-idf-

      - name: Install ESP toolchain
        run: |
          curl -LO https://github.com/esp-rs/espup/releases/latest/download/espup-x86_64-unknown-linux-gnu
          chmod +x espup-x86_64-unknown-linux-gnu
          ./espup-x86_64-unknown-linux-gnu install
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build documentation
        env:
          ESP_IDF_VERSION: v5.1
          ESP_IDF_SDKCONFIG_DEFAULTS: $(pwd)/sdkconfig.defaults
          RUSTDOCFLAGS: --enable-index-page -Zunstable-options
        run: |
          source $HOME/export-esp.sh
          cargo doc --no-deps --document-private-items

      - name: Add index redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=esp32_s3_display_dashboard/index.html">' > target/doc/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/doc

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4